use serde::{Deserialize, Serialize};
use std::path::PathBuf;

use crate::{
    app::{AppContext, AppState, config::AppConfig},
    file_handling::{
        Explorer, SearchResult,
        metadata::{DirMetadata, FileMetadata},
    },
    ui::{Theme, search_widget::SearchMode},
};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
/// Enum that tracks all the actions that can be carried out by the App
pub enum Action {
    ApplyAppSettings(AppConfig),
    ApplySettingsInput,
    CloseMetadata,
    DropDownClosed,
    DropDownShowing,
    Error(String),
    ExportDone,
    ExportFailure(String),
    ForcedShutdown,
    HideOrShowSystemOverview,
    Init,
    LoadDir(PathBuf, bool),
    LoadDirDone(Explorer),
    LoadDirMetadata(String, PathBuf, bool),
    LoadDirMetadataDone(Option<DirMetadata>),
    None,
    Quit,
    Render,
    Resize(u16, u16),
    Resume,
    SettingsInputCanceled,
    SettingsInputShowing,
    SearchDone(Option<SearchResult>),
    SetCommandDescription(Option<String>),
    ShowAbout(AppContext),
    ShowDirMetadata(DirMetadata),
    ShowFileMetadata(PathBuf, FileMetadata),
    ShowHelp(AppContext),
    ShowResultsPage(SearchResult, SearchMode),
    ShowSearchPage(PathBuf),
    ShowSettings(AppContext),
    StartSearch(PathBuf, String, usize, bool),
    Suspend,
    SwitchAppContext(AppContext),
    Tick,
    ToggleTheme(Theme),
    UpdateAppState(AppState),
}

// pub enum Action {
//     DropDownShowing,
//     DropDownClosed,
//     Error(String),
//     ExportDone,
//     ExportFailure(String),
//     HideOrShowSystemOverview,
//     Init,
//     LoadDir(PathBuf, bool),
//     LoadDirDone(Explorer),
//     LoadDirMetadata(String, PathBuf, bool),
//     LoadDirMetadataDone(Option<DirMetadata>),
//     None,
//     Quit,
//     Render,
//     Resize(u16, u16),
//     Resume,
//     SearchDone(Option<SearchResult>),
//     SetCommandDescription(Option<String>),
//     ShowAbout(AppContext),
//     ShowDirMetadata(DirMetadata),
//     ShowFileMetadata(PathBuf, FileMetadata),
//     ShowHelp(AppContext),
//     CloseMetadata,
//     ShowResultsPage(SearchResult, SearchMode),
//     ShowSearchPage(PathBuf),
//     ShowSettings(AppContext),
//     ApplySettings(AppConfig),
//     StartSearch(PathBuf, String, usize, bool),
//     Suspend,
//     SwitchAppContext(AppContext),
//     Tick,
//     ForcedShutdown,
//     ToggleTheme(Theme),
//     UpdateAppState(AppState),
// }
